spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/eqcm?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:citech123!}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        show_sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:temp}
jwt:
  secret: ${JWT_SECRET_KEY:"249526a8897e06af7d405b9705f3611f56fe4f4e6d55e078f52cd7e979f952aeb5a716d72939b51abd84ff8b9fbbb6427828890d7262cedcbef827e62452be84="}
