spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: ALWAYS
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:eqcm}?useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:temp}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
        show_sql: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:temp}
jwt:
  secret: ${JWT_SECRET_KEY:"249526a8897e06af7d405b9705f3611f56fe4f4e6d55e078f52cd7e979f952aeb5a716d72939b51abd84ff8b9fbbb6427828890d7262cedcbef827e62452be84="}

social:
  client:
    naver:
      client-id: ${NAVER_CLIENT_ID:test}
      client-secret: ${NAVER_SECRET_KEY:test}
      redirect-uri: ${NAVER_REDIRECT_URI:http://localhost:8080/login/naver}
      grant-type: authorization_code
